# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='example_plugins_tableauview', serialize=False, to='cms.CMSPlugin')),
                ('site_root', models.CharField(default='', help_text='The site root of the Tableau site hosting the View', max_length=50, verbose_name='Site Root')),
                ('workbook_name', models.CharField(default='', help_text='The Workbook that contains the View', max_length=50, verbose_name='Workbook Name')),
                ('view_name', models.CharField(default='', help_text='The name of the View', max_length=50, verbose_name='View Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
