# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableauview',
            name='site_root',
            field=models.CharField(default='downpatproductions', help_text='The site root of the Tableau site hosting the View', max_length=50, verbose_name='Site Root'),
        ),
    ]
